package core

import (
	"crypto/sha256"
	"encoding/json"
	"errors"
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/byteplus-sdk/byteplus-sdk-go-rec-core/logs"
	"github.com/byteplus-sdk/byteplus-sdk-go-rec-core/option"
	"github.com/google/uuid"
	"github.com/valyala/fasthttp"
	"google.golang.org/protobuf/proto"
)

const (
	netErrMark     = "[netErr]"
	defaultTimeout = time.Second * 5
)

type httpCaller struct {
	tenantID        string
	useAirAuth      bool
	volcCredentials credential
	airAuthToken    string
	httpCli         *fasthttp.Client
}

func (c *httpCaller) doJsonRequest(url string, request interface{},
	response interface{}, options *option.Options) error {
	reqBytes, err := json.Marshal(request)
	if err != nil {
		logs.Error("[ByteplusSDK] json marshal request fail, err:%v url:%s", err, url)
		return err
	}
	headers := c.buildHeaders(options, "application/json")
	url = c.withOptionQueries(options, url)
	rspBytes, err := c.doHttpRequest(url, headers, reqBytes, options.Timeout)
	if err != nil {
		return err
	}
	err = json.Unmarshal(rspBytes, &response)
	if err != nil {
		logs.Error("[ByteplusSDK] unmarshal response fail, err:%v url:%s", err, url)
		return err
	}
	return nil
}

func (c *httpCaller) doPbRequest(url string, request proto.Message,
	response proto.Message, options *option.Options) error {
	reqBytes, err := proto.Marshal(request)
	if err != nil {
		logs.Error("[ByteplusSDK] marshal request fail, err:%v url:%s", err, url)
		return err
	}
	headers := c.buildHeaders(options, "application/x-protobuf")
	url = c.withOptionQueries(options, url)
	rspBytes, err := c.doHttpRequest(url, headers, reqBytes, options.Timeout)
	if err != nil {
		return err
	}
	err = proto.Unmarshal(rspBytes, response)
	if err != nil {
		logs.Error("[ByteplusSDK] unmarshal response fail, err:%v url:%s", err, url)
		return err
	}
	return nil
}

func (c *httpCaller) buildHeaders(options *option.Options, contentType string) map[string]string {
	headers := make(map[string]string)
	headers["Content-Encoding"] = "gzip"
	headers["Accept-Encoding"] = "gzip"
	headers["Content-Type"] = contentType
	headers["Accept"] = contentType
	headers["Tenant-Id"] = c.tenantID
	c.withOptionHeaders(headers, options)
	return headers
}

func (c *httpCaller) withOptionHeaders(headers map[string]string, options *option.Options) {
	if len(options.RequestID) == 0 {
		requestID := uuid.NewString()
		logs.Info("[ByteplusSDK] requestID is generated by sdk: '%s' ", requestID)
		headers["Request-Id"] = requestID
	} else {
		headers["Request-Id"] = options.RequestID
	}
	if options.ServerTimeout > 0 {
		headers["Timeout-Millis"] = strconv.Itoa(int(options.ServerTimeout.Milliseconds()))
	}
	for k, v := range options.Headers {
		headers[k] = v
	}
}

func (c *httpCaller) withAuthHeaders(req *fasthttp.Request, reqBytes []byte) {
	if !c.useAirAuth {
		c.withVolcAuthHeaders(req)
		return
	}
	c.withAirAuthHeaders(req, reqBytes)
}

func (c *httpCaller) withAirAuthHeaders(req *fasthttp.Request, reqBytes []byte) {
	var (
		// Gets the second-level timestamp of the current time.
		// The server only supports the second-level timestamp.
		// The 'ts' must be the current time.
		// When current time exceeds a certain time, such as 5 seconds, of 'ts',
		// the signature will be invalid and cannot pass authentication
		ts = strconv.FormatInt(time.Now().Unix(), 10)
		// Use sub string of UUID as "nonce",  too long will be wasted.
		// You can also use 'ts' as' nonce'
		nonce = uuid.NewString()[:8]
		// calculate the authentication signature
		signature = c.calSignature(reqBytes, ts, nonce)
	)
	req.Header.Set("Tenant-Ts", ts)
	req.Header.Set("Tenant-Nonce", nonce)
	req.Header.Set("Tenant-Signature", signature)
}

func (c *httpCaller) withVolcAuthHeaders(req *fasthttp.Request) {
	volcSign(req, c.volcCredentials)
}

func (c *httpCaller) calSignature(reqBytes []byte, ts, nonce string) string {
	var (
		token    = c.airAuthToken
		tenantID = c.tenantID
	)
	// Splice in the order of "token", "HttpBody", "tenant_id", "ts", and "nonce".
	// The order must not be mistaken.
	// String need to be encoded as byte arrays by UTF-8
	shaHash := sha256.New()
	shaHash.Write([]byte(token))
	shaHash.Write(reqBytes)
	shaHash.Write([]byte(tenantID))
	shaHash.Write([]byte(ts))
	shaHash.Write([]byte(nonce))
	return fmt.Sprintf("%x", shaHash.Sum(nil))
}

func (c *httpCaller) withOptionQueries(options *option.Options, url string) string {
	var queriesParts []string
	for name, value := range options.Queries {
		queriesParts = append(queriesParts, name+"="+value)
	}
	optionQuery := strings.Join(queriesParts, "&")
	if optionQuery == "" {
		return url
	}
	if strings.Contains(url, "?") {
		url = url + "&" + optionQuery
	} else {
		url = url + "?" + optionQuery
	}
	return url
}

func (c *httpCaller) doHttpRequest(url string, headers map[string]string,
	reqBytes []byte, timeout time.Duration) ([]byte, error) {
	reqBytes = fasthttp.AppendGzipBytes(nil, reqBytes)

	request := c.acquireRequest(url, headers, reqBytes)
	response := fasthttp.AcquireResponse()
	defer func() {
		fasthttp.ReleaseRequest(request)
		fasthttp.ReleaseResponse(response)
	}()
	c.withAuthHeaders(request, reqBytes)
	start := time.Now()
	defer func() {
		logs.Debug("[ByteplusSDK] http url:%s, cost:%s", url, time.Now().Sub(start))
	}()
	logs.Trace("[ByteplusSDK] http request header:\n%s", &request.Header)
	if timeout <= 0 {
		timeout = defaultTimeout
	}
	err := c.httpCli.DoTimeout(request, response, timeout)
	if err != nil {
		if strings.Contains(strings.ToLower(err.Error()), "timeout") {
			logs.Error("[ByteplusSDK] do http request timeout, err:%v url:%s", err, url)
			return nil, errors.New(netErrMark + " timeout")
		}
		logs.Error("[ByteplusSDK] do http request occur error, err:%v url:%s", err, url)
		return nil, err
	}
	logs.Trace("[ByteplusSDK] http response url:%s headers:\n%s", url, &response.Header)
	if response.StatusCode() != fasthttp.StatusOK {
		c.logFailureStatus(url, response)
		return nil, errors.New(netErrMark + "http status not 200")
	}
	return decompressResponse(url, response)
}

func (c *httpCaller) acquireRequest(url string,
	headers map[string]string, reqBytes []byte) *fasthttp.Request {
	request := fasthttp.AcquireRequest()
	request.Header.SetMethod(fasthttp.MethodPost)
	request.SetRequestURI(url)
	for k, v := range headers {
		request.Header.Set(k, v)
	}
	request.SetBodyRaw(reqBytes)
	return request
}

func (c *httpCaller) logFailureStatus(url string, response *fasthttp.Response) {
	rspBytes, _ := decompressResponse(url, response)
	if len(rspBytes) > 0 {
		logs.Error("[ByteplusSDK] http status not 200, url:%s code:%d headers:\n%s%s\n",
			url, response.StatusCode(), &response.Header, string(rspBytes))
		return
	}
	logs.Error("[ByteplusSDK] http status not 200, url:%s code:%d headers:\n%s\n",
		url, response.StatusCode(), &response.Header)
}

func decompressResponse(url string, response *fasthttp.Response) ([]byte, error) {
	contentEncoding := strings.ToLower(strings.TrimSpace(string(response.Header.Peek("Content-Encoding"))))
	switch contentEncoding {
	case "gzip":
		respBodyBytes, err := response.BodyGunzip()
		if err != nil {
			logs.Error("[ByteplusSDK] decompress gzip resp occur error, "+
				"msg:%v url:%s header:\n%s", err, url, &response.Header)
			return nil, err
		}
		return respBodyBytes, nil
	case "":
		return response.Body(), nil
	default:
		logs.Error("[ByteplusSDK] receive unsupported response "+
			"content encoding:%s url:%s header:\n%s", contentEncoding, url, &response.Header)
		err := errors.New("unsupported resp content encoding:" + contentEncoding)
		return nil, err
	}
}
